# free-threaded-python-id-bug
This repo contains a minimal reproducible case for a mismatch between id() in Cython and CPython in 313t
